name: Publish Website

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '22 7 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-20.04
    env:
      WX_SITE_DIR: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: 'false'
      - name: Yarn Install
        run: yarn
      - name: Compile Assets
        run: yarn dist
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Bundle Cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-ruby-2.6-ubuntu-20.04-${{ hashFiles('Gemfile.lock') }}
          restore-keys: bundle-ruby-2.6-ubuntu-20.04-
      - name: Bundle Install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Update Release Info
        run: ruby update_release_info.rb
      - name: Update Download Stats
        run: ruby _cron/update_download_stats.rb
      - name: Download Locales
        run: svn checkout https://github.com/wxWidgets/wxWidgets/trunk/locale/ _cron/locale
      - name: Update Translation Stats
        run: sudo apt install gettext && ./_cron/update_translation_stats.sh
      - name: Update wxXRC Schema
        run: _cron/update_wxxrc_schema.sh
      - name: Build
        run: bundle exec jekyll build
      - name: Upload
        if: github.repository_owner == 'wxWidgets' && github.ref == 'refs/heads/master'
        env:
          REMOTE_KEY: ${{secrets.REMOTE_KEY}}
          REMOTE_PATH: ${{secrets.REMOTE_PATH}}
        run: |
          mkdir "$HOME/.ssh"
          echo "$REMOTE_KEY" > "$HOME/.ssh/remote_key"
          chmod 600 "$HOME/.ssh/remote_key"
          rsync -crz --delete -e "ssh -i $HOME/.ssh/remote_key -o StrictHostKeyChecking=no" _site/ "$REMOTE_PATH"
